# Generated by Django 5.2.1 on 2025-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0006_alter_race_race_date_alter_team_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(),
        ),
    ]
