# Generated by Django 5.2.1 on 2025-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0008_team_primary_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='primary_driver',
        ),
        migrations.AlterField(
            model_name='race',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='country',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='driver',
            field=models.ManyToManyField(related_name='races', to='racing.driver'),
        ),
    ]
