# Generated by Django 5.2.1 on 2025-06-17 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0009_remove_team_primary_driver_alter_race_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='racing.team'),
        ),
        migrations.AlterField(
            model_name='race',
            name='driver',
            field=models.ManyToManyField(blank=True, related_name='races', to='racing.driver'),
        ),
    ]
